name: bg_launcher
description: A flutter plugin that brings an in-background android app to the foreground (Android only)
version: 0.0.2
homepage: https://github.com/X-SLAYER/bg_launcher

environment:
  sdk: ">=2.17.1 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: slayer.bg.launcher.bg_launcher
        pluginClass: BgLauncherPlugin